spring.application.name=Flight

spring.datasource.url=jdbc:postgresql://localhost:5432/flightdb
spring.datasource.username=postgres
spring.datasource.password=ipm@1605

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8083